"""aiocortex — Async Python library for Home Assistant configuration management."""

from ._version import __version__
from .exceptions import (
    CortexError,
    FileError,
    GitError,
    GitNotInitializedError,
    PathSecurityError,
    YAMLParseError,
)
from .files import AsyncFileManager, YAMLEditor
from .git import GitManager
from .instructions import (
    async_load_all_instructions,
    async_load_instruction_file,
    get_instruction_files,
    load_all_instructions,
    load_instruction_file,
)
from .models import (
    AutomationConfig,
    CheckpointResult,
    CleanupResult,
    CommitInfo,
    CortexResponse,
    FileAppendResult,
    FileDeleteResult,
    FileInfo,
    FilePathResult,
    FileWriteResult,
    HelperSpec,
    PendingChanges,
    PendingChangesSummary,
    RestoreFilesResult,
    RollbackResult,
    ScriptConfig,
    ServiceCallSpec,
    TransactionAbortResult,
    TransactionCommitResult,
    TransactionOperation,
    TransactionRollbackMetadata,
    TransactionState,
    TransactionValidationResult,
    YAMLConflict,
    YAMLPatchOperation,
    YAMLPatchPreview,
)

__all__ = [
    "AsyncFileManager",
    "AutomationConfig",
    "CheckpointResult",
    "CleanupResult",
    "CommitInfo",
    "CortexError",
    "CortexResponse",
    "FileAppendResult",
    "FileDeleteResult",
    "FileError",
    "FileInfo",
    "FilePathResult",
    "FileWriteResult",
    "GitError",
    "GitManager",
    "GitNotInitializedError",
    "HelperSpec",
    "PathSecurityError",
    "PendingChanges",
    "PendingChangesSummary",
    "RestoreFilesResult",
    "RollbackResult",
    "ScriptConfig",
    "ServiceCallSpec",
    "TransactionAbortResult",
    "TransactionCommitResult",
    "TransactionOperation",
    "TransactionRollbackMetadata",
    "TransactionState",
    "TransactionValidationResult",
    "YAMLConflict",
    "YAMLEditor",
    "YAMLParseError",
    "YAMLPatchOperation",
    "YAMLPatchPreview",
    "__version__",
    "async_load_all_instructions",
    "async_load_instruction_file",
    "get_instruction_files",
    "load_all_instructions",
    "load_instruction_file",
]
